[package]
name = "igra-kaspa"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
hex = "0.4"
jni = "0.21"
kaspa-addresses = { git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "895766fd6e882e5ebf1ede74f9de610d616afa14" }
kaspa-bip32 = { git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "895766fd6e882e5ebf1ede74f9de610d616afa14" }
kaspa-consensus-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "895766fd6e882e5ebf1ede74f9de610d616afa14" }
kaspa-grpc-client = { git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "895766fd6e882e5ebf1ede74f9de610d616afa14" }
kaspa-rpc-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "895766fd6e882e5ebf1ede74f9de610d616afa14" }
kaspa-txscript = { git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "895766fd6e882e5ebf1ede74f9de610d616afa14" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
